language: python

python:
  - 2.6
  - 3.3

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -q --use-mirrors Cython numpy
  - pip install coverage
  - pip install coveralls
  # For Python 2.6 we also need argparse
  - pip install argparse
  - python -V

install:
  - pip install .

script:
  - python runtests.py -n -m full --coverage
after_success:
    - coveralls
