package:
  name: pywt
  version: master

source:
  git_url: https://github.com/nigma/pywt.git
  git_tag: master

#build:
#  script: python setup.py install

requirements:
  build:
    - cython
    - python
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pywt

about:
  license: MIT
  home: http://www.pybytes.com/pywavelets/
  summary: PyWavelets, wavelet transform module
